[meta]
  title = "Flask Live Transcription Starter"
  description = "Get started using Deepgram's Live Transcription with this Flask demo app"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "Live STT"
  language = "Python"
  framework = "Flask"

[build]
  command = "pip install -r requirements.txt"

[config]
  sample = "sample.env"
  output = ".env"

[post-build]
  message = "Run `python app.py` to get up and running." # message to give users once setup is complete
